### ISSUE TITLE
PowerPoints

### ISSUE THREAD

**Issue by Williams-Nest** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#28]
Where can we as MCT's comment on errors in other part of the materials?
The zip files with slides are the same for day 1 and day 2

**Comment by polichtm** [comment]
Hi Michael,
You might want to refer to the trainer prep guide on the MCT download Center, which states that this is intentional (the zip files for both deliveries are the same).
If you have any additional questions regarding this or any other non-lab MCT related topic, you can use the MCT courseware Forum
rgds
Marcin
