### ISSUE TITLE
Free tier 

### ISSUE THREAD

**Issue by nbicsi** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#30]
# Module: AZ-900T0x
#### Step: 04

Description of issue
- Setting free tier does not work. Erro message contains: "Available tiers: [Sandard]"

Repro steps:
- Trying to create the Azure IoT Hub instance selecting the Free or Basic tier will fail. Selecting 'Standard' tier works.

**Comment by itbland** [comment]
I have confirmed this error for EastUS, but I am able to create it in WestUS; This is likely a temporary block of that size in the EastUS region (and possibly others). Note that you must completely delete the failed hub before you can create one in another region, as only one free tier hub is allowed per subscription.
HTH
Eric Bland, MCT

**Comment by itbland** [comment]
Update: The IoT Hub **_IS_** created, the problem is that it is also trying to create a link to the Azure Security Center, which is not supported on a Free tier hub. This appears to be an error in the Azure Portal. 
As a work-around, "**_switch off_**" Azure Security Center _**BEFORE**_ you select Free tier and it seems to work without error.
![image](https://user-images.githubusercontent.com/20519564/75059975-95ed9800-54a3-11ea-9ee8-714b4419181e.png)

**Comment by polichtm** [comment]
switched to Basic B1
rgds
Marcin
