### ISSUE TITLE
P4$$w0rd1234

### ISSUE THREAD

**Issue by james-grant1** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#58]
# Module: 02
#### Step: 04

Description of issue:

Demo-ing the lab, I naively followed the script verbatim, mostly to simplify for myself and students 
Unfortunately I was then unable to connect to the VM, and spent X minutes trying to debug what I assumed was my Azure related mistake.
After the fact I remembered that `$` is of course a special Linux character and `$$` evaluates as the PID of the current shell.
`P4$$w0rd1234` is evaluated as a legitimate password since it still meets the conditions, but users don't know what it is.

Repro steps:

Follow the steps

**Solution** would be to change the `password` -> `P455w0rd1234!` and possibly for the other labs that use it?

**Comment by R-C-Stewart** [comment]
Very interesting find and we will look at the possibility of updating this for the next full refresh of the courses; but it will not be an immediate fix.  I say this because 17 or the 23 labs use this password; so it would take a large effort make the change across all the labs and platforms; then ensure that it got tested and updated.  Not downplaying the validity of the issue, just noting it will be a while in the fixing.
